"""Chat tool schemas and executors for AI Advisory Chat.

Tools allow the LLM to query the Estonian Legal Ontology, search
provisions, inspect draft impact reports, and retrieve provision details.
Each executor is an async function that receives the tool input dict and
a ``SparqlClient`` instance.

CRITICAL: All SPARQL queries generated by the LLM pass through
``_is_read_only_sparql`` to reject any mutation (UPDATE/DELETE/INSERT).
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any
from uuid import UUID

from app.db import get_connection
from app.ontology.sparql_client import SparqlClient, _sanitize_sparql_value

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Tool schemas (Claude tool_use format)
# ---------------------------------------------------------------------------

CHAT_TOOLS: list[dict[str, Any]] = [
    {
        "name": "query_ontology",
        "description": (
            "Execute a SPARQL query against the Estonian Legal Ontology to find "
            "legal provisions, court decisions, EU legislation, and their relationships."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": (
                        "SPARQL SELECT query. Use the estleg: prefix for "
                        "Estonian legal ontology URIs."
                    ),
                },
            },
            "required": ["query"],
        },
    },
    {
        "name": "search_provisions",
        "description": (
            "Search legal provisions by keyword. Returns matching provisions "
            "with their paragraph references and summaries."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "keywords": {
                    "type": "string",
                    "description": "Search keywords in Estonian",
                },
                "limit": {"type": "integer", "default": 10},
            },
            "required": ["keywords"],
        },
    },
    {
        "name": "get_draft_impact",
        "description": (
            "Get the impact analysis report for a specific draft legislation document."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "draft_id": {
                    "type": "string",
                    "description": "UUID of the draft",
                },
            },
            "required": ["draft_id"],
        },
    },
    {
        "name": "get_provision_details",
        "description": (
            "Get detailed information about a specific legal provision including "
            "its text, source act, and related provisions."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "provision_uri": {
                    "type": "string",
                    "description": ("Ontology URI of the provision (e.g., estleg:KarS_Norm_001)"),
                },
            },
            "required": ["provision_uri"],
        },
    },
]


# ---------------------------------------------------------------------------
# SPARQL safety
# ---------------------------------------------------------------------------

# Strip SPARQL single-line comments before validation so attackers cannot
# hide mutation keywords behind ``# SELECT ...`` misdirection.
# Only match ``#`` that is NOT inside a URI (``<...>``) by requiring
# the ``#`` to appear at start-of-line or after whitespace.
_COMMENT_PATTERN = re.compile(r"(?:^|(?<=\s))#[^\n]*", re.MULTILINE)

# Allowed SPARQL query forms (whitelist approach).
_ALLOWED_QUERY_FORMS = re.compile(
    r"^(SELECT|ASK|DESCRIBE|CONSTRUCT)\b",
    re.IGNORECASE,
)

# Block SERVICE keyword to prevent SSRF via federated queries.
_SERVICE_PATTERN = re.compile(r"\bSERVICE\b", re.IGNORECASE)


def _is_read_only_sparql(query: str) -> bool:
    """Return True if *query* is a safe read-only SPARQL query.

    Uses a whitelist approach:
    1. Strip comments (``#...`` to end of line).
    2. Strip leading PREFIX/BASE declarations.
    3. Verify the query body starts with SELECT, ASK, DESCRIBE, or CONSTRUCT.
    4. Block the SERVICE keyword anywhere (prevents SSRF via federated queries).
    """
    # Strip comments
    cleaned = _COMMENT_PATTERN.sub("", query)

    # Block SERVICE keyword anywhere in the query
    if _SERVICE_PATTERN.search(cleaned):
        return False

    # Strip leading whitespace and PREFIX/BASE declarations line by line
    body = cleaned.strip()
    while True:
        m = re.match(r"(?i)\s*PREFIX\s+\S+:\s*<[^>]*>\s*", body)
        if m:
            body = body[m.end() :]
            continue
        m = re.match(r"(?i)\s*BASE\s*<[^>]*>\s*", body)
        if m:
            body = body[m.end() :]
            continue
        break

    body = body.lstrip()

    # Verify the query starts with an allowed form
    return _ALLOWED_QUERY_FORMS.match(body) is not None


# ---------------------------------------------------------------------------
# Tool executors
# ---------------------------------------------------------------------------


async def _exec_query_ontology(
    tool_input: dict[str, Any],
    sparql: SparqlClient,
) -> dict[str, Any]:
    """Execute an arbitrary read-only SPARQL query."""
    query = tool_input.get("query", "")
    if not query.strip():
        return {"error": "Empty SPARQL query"}

    if not _is_read_only_sparql(query):
        return {
            "error": "Only read-only SPARQL queries (SELECT/ASK/DESCRIBE/CONSTRUCT) are allowed"
        }

    results = sparql.query(query)
    return {"results": results}


async def _exec_search_provisions(
    tool_input: dict[str, Any],
    sparql: SparqlClient,
) -> dict[str, Any]:
    """Search provisions by keyword using SPARQL FILTER(CONTAINS())."""
    keywords = tool_input.get("keywords", "")
    if not keywords.strip():
        return {"error": "Empty keywords"}

    limit = tool_input.get("limit", 10)
    if not isinstance(limit, int) or limit <= 0:
        limit = 10
    if limit > 100:
        limit = 100

    safe_keywords = _sanitize_sparql_value(keywords)

    query = f"""
        PREFIX estleg: <http://ontology.seadusloome.ee/>
        PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

        SELECT ?uri ?paragrahv ?summary ?source_act
        WHERE {{
            ?uri a estleg:Provision .
            OPTIONAL {{ ?uri estleg:paragrahv ?paragrahv . }}
            OPTIONAL {{ ?uri rdfs:comment ?summary . }}
            OPTIONAL {{ ?uri estleg:sourceAct ?source_act . }}
            FILTER(
                CONTAINS(LCASE(STR(?paragrahv)), LCASE("{safe_keywords}"))
                || CONTAINS(LCASE(STR(?summary)), LCASE("{safe_keywords}"))
            )
        }}
        LIMIT {limit}
    """
    results = sparql.query(query)
    provisions = [
        {
            "uri": row.get("uri", ""),
            "paragrahv": row.get("paragrahv", ""),
            "summary": row.get("summary", ""),
            "source_act": row.get("source_act", ""),
        }
        for row in results
    ]
    return {"provisions": provisions}


async def _exec_get_draft_impact(
    tool_input: dict[str, Any],
    sparql: SparqlClient,
    auth: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Read the latest impact report for a given draft from the DB.

    The query joins with the ``drafts`` table and filters by the
    caller's ``org_id`` to prevent cross-organisation data access.
    """
    draft_id = tool_input.get("draft_id", "")
    if not draft_id.strip():
        return {"error": "Empty draft_id"}

    # M3: validate draft_id is a proper UUID
    try:
        UUID(draft_id)
    except (ValueError, TypeError):
        return {"error": "Invalid draft_id format"}

    # H2: org-scoping — require auth with org_id
    org_id: str | None = None
    if auth:
        org_id = auth.get("org_id")

    if not org_id:
        return {"error": "Authentication with org_id required"}

    try:
        with get_connection() as conn:
            row = conn.execute(
                """
                SELECT ir.report_data
                FROM impact_reports ir
                JOIN drafts d ON d.id = ir.draft_id
                WHERE ir.draft_id = %s AND d.org_id = %s
                ORDER BY ir.generated_at DESC
                LIMIT 1
                """,
                (draft_id, org_id),
            ).fetchone()
    except Exception:
        logger.exception("Failed to fetch impact report for draft_id=%s", draft_id)
        return {"error": "Failed to read impact report from database"}

    if row is None:
        return {"error": f"No impact report found for draft {draft_id}"}

    report_data = row[0]
    if isinstance(report_data, str):
        try:
            report_data = json.loads(report_data)
        except json.JSONDecodeError:
            pass

    return {"report": report_data}


async def _exec_get_provision_details(
    tool_input: dict[str, Any],
    sparql: SparqlClient,
) -> dict[str, Any]:
    """SPARQL query for detailed information about a single provision."""
    provision_uri = tool_input.get("provision_uri", "")
    if not provision_uri.strip():
        return {"error": "Empty provision_uri"}

    safe_uri = _sanitize_sparql_value(provision_uri)

    # If the URI uses the estleg: prefix, expand it for the VALUES clause.
    # Otherwise treat it as a full URI.
    if safe_uri.startswith("estleg:"):
        uri_ref = safe_uri  # keep as prefixed name
        filter_clause = f"BIND({uri_ref} AS ?uri)"
    else:
        filter_clause = f"BIND(<{safe_uri}> AS ?uri)"

    query = f"""
        PREFIX estleg: <http://ontology.seadusloome.ee/>
        PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

        SELECT ?uri ?text ?sourceAct ?paragrahv ?related ?relLabel
        WHERE {{
            {filter_clause}
            OPTIONAL {{ ?uri estleg:text ?text . }}
            OPTIONAL {{ ?uri estleg:sourceAct ?sourceAct . }}
            OPTIONAL {{ ?uri estleg:paragrahv ?paragrahv . }}
            OPTIONAL {{
                ?uri estleg:relatedTo ?related .
                OPTIONAL {{ ?related rdfs:label ?relLabel . }}
            }}
        }}
    """
    results = sparql.query(query)

    if not results:
        return {"error": f"Provision not found: {provision_uri}"}

    first = results[0]
    related_list = []
    for row in results:
        rel = row.get("related", "")
        if rel:
            related_list.append(
                {
                    "uri": rel,
                    "label": row.get("relLabel", ""),
                }
            )

    return {
        "provision": {
            "uri": first.get("uri", provision_uri),
            "text": first.get("text", ""),
            "source_act": first.get("sourceAct", ""),
            "paragrahv": first.get("paragrahv", ""),
            "related": related_list,
        }
    }


# ---------------------------------------------------------------------------
# Executor dispatcher
# ---------------------------------------------------------------------------

_EXECUTORS: dict[str, Any] = {
    "query_ontology": _exec_query_ontology,
    "search_provisions": _exec_search_provisions,
    "get_draft_impact": _exec_get_draft_impact,
    "get_provision_details": _exec_get_provision_details,
}


async def execute_tool(
    tool_name: str,
    tool_input: dict[str, Any],
    sparql: SparqlClient,
    auth: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Dispatch a tool call to the appropriate executor.

    Returns a dict with either the tool's results or an ``"error"`` key.
    Executor exceptions are caught and returned as error dicts (never crash).

    Parameters
    ----------
    auth:
        Auth dict from the caller (must have ``org_id`` for tools that
        require org-scoping, e.g. ``get_draft_impact``).
    """
    fn = _EXECUTORS.get(tool_name)
    if fn is None:
        return {"error": f"Unknown tool: {tool_name}"}
    try:
        # Thread auth to executors that accept it.
        import inspect

        sig = inspect.signature(fn)
        if "auth" in sig.parameters:
            return await fn(tool_input, sparql, auth=auth)
        return await fn(tool_input, sparql)
    except Exception as e:
        logger.exception("Tool %s failed", tool_name)
        return {"error": str(e)[:200]}
