"""Chat tool schemas and executors for AI Advisory Chat.

Tools allow the LLM to query the Estonian Legal Ontology, search
provisions, inspect draft impact reports, and retrieve provision details.
Each executor is an async function that receives the tool input dict and
a ``SparqlClient`` instance.

CRITICAL: All SPARQL queries generated by the LLM pass through
``_is_read_only_sparql`` to reject any mutation (UPDATE/DELETE/INSERT)
**and** through :func:`app.ontology.scoping.assert_public_only` to reject
any ``GRAPH`` / ``FROM`` / ``FROM NAMED`` keyword — so an LLM-authored
query can only ever read the public default graph, never an org-private
draft named graph (#844 C1). Results are additionally capped (row count,
serialised bytes, and an injected ``LIMIT``) so a runaway query cannot
return 90k+ rows (#844 G1).
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any
from uuid import UUID

from app.db import get_connection
from app.ontology.relations import PREDICATES
from app.ontology.scoping import assert_public_only
from app.ontology.sparql_client import SparqlClient, _sanitize_sparql_value

# Strict validation patterns for provision URIs (prevents SPARQL injection).
# Prefixed names: only alphanumeric, underscore, hyphen after "estleg:"
_SAFE_PREFIXED_RE = re.compile(r"^estleg:[A-Za-z0-9_\-]+$")
# Full URIs: strict character allowlist (matches SparqlClient._inject_uri_bindings)
_SAFE_FULL_URI_RE = re.compile(r"^https?://[A-Za-z0-9./:_#\-]{1,512}$")

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Tool schemas (Claude tool_use format)
# ---------------------------------------------------------------------------

CHAT_TOOLS: list[dict[str, Any]] = [
    {
        "name": "query_ontology",
        "description": (
            "Execute a SPARQL query against the Estonian Legal Ontology to find "
            "legal provisions, court decisions, EU legislation, and their relationships."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": (
                        "SPARQL SELECT query. Use the estleg: prefix for "
                        "Estonian legal ontology URIs."
                    ),
                },
            },
            "required": ["query"],
        },
    },
    {
        "name": "search_provisions",
        "description": (
            "Search legal provisions by keyword. Returns matching provisions "
            "with their paragraph references and summaries."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "keywords": {
                    "type": "string",
                    "description": "Search keywords in Estonian",
                },
                "limit": {"type": "integer", "default": 10},
            },
            "required": ["keywords"],
        },
    },
    {
        "name": "get_draft_impact",
        "description": (
            "Get the impact analysis report for a specific draft legislation document."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "draft_id": {
                    "type": "string",
                    "description": "UUID of the draft",
                },
            },
            "required": ["draft_id"],
        },
    },
    {
        "name": "get_provision_details",
        "description": (
            "Get detailed information about a specific legal provision including "
            "its text, source act, and related provisions."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "provision_uri": {
                    "type": "string",
                    "description": ("Ontology URI of the provision (e.g., estleg:KarS_Norm_001)"),
                },
            },
            "required": ["provision_uri"],
        },
    },
    # ---- C4 specialised helpers (2026-05-16) -------------------------------
    # These four tools cover the most frequent lawyer questions ("what court
    # decisions interpret this section?", "is this an EU transposition?",
    # "how has this been amended?", "what concepts does it define?"). The
    # LLM is steered toward them by the system prompt so it doesn't fall back
    # to hand-rolling SPARQL via ``query_ontology`` (which has a real
    # hallucination failure mode — wrong predicates, malformed FILTERs,
    # runaway joins). Every predicate is imported from
    # :mod:`app.ontology.relations`; nothing is hardcoded as ``estleg:*``
    # string in the templates.
    {
        "name": "get_court_decisions_for_provision",
        "description": (
            "List Supreme Court decisions (Riigikohus) that interpret or apply "
            "the given legal provision. Prefer this over query_ontology for "
            "court-practice questions. Returns ordered decisions with case "
            "metadata so they can be cited cleanly."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "provision_uri": {
                    "type": "string",
                    "description": ("Ontology URI of the provision (e.g., estleg:KarS_Norm_001)"),
                },
                "limit": {
                    "type": "integer",
                    "default": 25,
                    "description": "Max decisions to return (1-100, default 25).",
                },
            },
            "required": ["provision_uri"],
        },
    },
    {
        "name": "get_eu_transposition_for_provision",
        "description": (
            "Show the EU transposition / harmonisation links for the given "
            "Estonian legal provision (or its parent act). Prefer this over "
            "query_ontology for EU-compliance questions. Returns the EU acts "
            "with the relation type (transposesDirective / transposedBy / "
            "harmonisedWith) and the raw transpositionStatus literal where "
            "present so the caller can cite the official status."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "provision_uri": {
                    "type": "string",
                    "description": "Ontology URI of the provision.",
                },
                "limit": {
                    "type": "integer",
                    "default": 25,
                    "description": "Max EU acts to return (1-100, default 25).",
                },
            },
            "required": ["provision_uri"],
        },
    },
    {
        "name": "get_provision_amendments",
        "description": (
            "Return the ordered amendment history for the given provision. "
            "Prefer this over query_ontology for amendment / version-history "
            "questions. Includes both AmendmentEvent -> Provision (``amends``) "
            "and Provision -> Act/Draft (``amendedBy``) edges, ordered by "
            "validFrom date when available."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "provision_uri": {
                    "type": "string",
                    "description": "Ontology URI of the provision.",
                },
                "limit": {
                    "type": "integer",
                    "default": 50,
                    "description": "Max amendment rows (1-100, default 50).",
                },
            },
            "required": ["provision_uri"],
        },
    },
    {
        "name": "get_related_concepts",
        "description": (
            "List the legal concepts the provision defines plus the topic "
            "clusters it belongs to. Prefer this over query_ontology for "
            "conceptual / thematic questions. The query UNIONs the canonical "
            "``requestedCluster`` predicate with its SHACL alias "
            "``topicCluster`` for forward compatibility."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "provision_uri": {
                    "type": "string",
                    "description": "Ontology URI of the provision.",
                },
                "limit": {
                    "type": "integer",
                    "default": 25,
                    "description": "Max related rows (1-100, default 25).",
                },
            },
            "required": ["provision_uri"],
        },
    },
]


# ---------------------------------------------------------------------------
# SPARQL safety
# ---------------------------------------------------------------------------

# Strip SPARQL single-line comments before validation so attackers cannot
# hide mutation keywords behind ``# SELECT ...`` misdirection.
# Only match ``#`` that is NOT inside a URI (``<...>``) by requiring
# the ``#`` to appear at start-of-line or after whitespace.
_COMMENT_PATTERN = re.compile(r"(?:^|(?<=\s))#[^\n]*", re.MULTILINE)

# Allowed SPARQL query forms (whitelist approach).
#
# Restricted to SELECT + ASK only (#844 review). The tool's purpose is to
# *find* provisions / relationships (SELECT) and answer existence
# questions (ASK) — both bounded result shapes the executor knows how to
# cap. DESCRIBE and CONSTRUCT are rejected:
#   * DESCRIBE has no enforceable LIMIT in the bare ``DESCRIBE <uri>``
#     form and invites whole-public-graph server-side materialisation
#     that the post-query row cap cannot prevent.
#   * CONSTRUCT emits a graph (triples), not the binding rows the
#     executor's row/byte caps + ``_extract_bindings`` are built for, and
#     LIMIT-injection on it is not part of the tool's stated job.
_ALLOWED_QUERY_FORMS = re.compile(
    r"^(SELECT|ASK)\b",
    re.IGNORECASE,
)

# ---------------------------------------------------------------------------
# Literal/comment-aware SPARQL pre-processing
# ---------------------------------------------------------------------------
#
# LIMIT detection is an *allow-list* decision ("this query already has a
# LIMIT, so don't add one"), so it MUST NOT be fooled by the keyword
# appearing inside a string literal or a comment — otherwise an attacker
# writes ``SELECT … FILTER(CONTAINS(?x, "LIMIT 5")) …`` and skips
# injection, leaving the query uncapped at the server. We therefore strip
# string literals AND comments before scanning for ``LIMIT``.
#
# (The GRAPH/FROM rejection in ``app.ontology.scoping`` is a *deny-list*
# decision scanning raw text; a literal there can only cause a harmless
# false rejection, never a bypass, so it is left as-is by design.)
#
# A single combined scanner matching, in priority order at each position:
#   1. a triple-quoted literal ('''…''' / """…""")
#   2. a single-quoted literal ('…' / "…", no raw newline)
#   3. a ``#`` comment to end-of-line
# Scanning left-to-right with one alternation avoids the literal-vs-comment
# ordering hazard (a ``#`` inside a string, or a quote inside a comment, is
# consumed by whichever construct opened first). All escape sequences are
# honoured so a ``\'`` / ``\"`` inside a literal does not close it early.
_LITERAL_OR_COMMENT = re.compile(
    r"'''(?:\\.|[^\\])*?'''"  # '''...'''  (escape-aware, may span lines)
    r'|"""(?:\\.|[^\\])*?"""'  # """..."""
    r"|'(?:\\.|[^'\\\n])*'"  # '...'  (no raw newline)
    r'|"(?:\\.|[^"\\\n])*"'  # "..."
    r"|(?:^|(?<=\s))#[^\n]*",  # # comment to end-of-line
    re.DOTALL | re.MULTILINE,
)


def _strip_literals_and_comments(query: str) -> str:
    """Return *query* with string literals and ``#`` comments blanked.

    A single left-to-right pass replaces each string literal with ``""``
    (a harmless empty literal) and each comment with the empty string, so
    a subsequent keyword scan (e.g. for ``LIMIT``) only ever sees the
    query's *structure*, never user-controlled text. Using one combined
    pattern means a ``#`` inside a literal stays part of the literal and a
    quote inside a comment stays part of the comment — no ordering hazard.
    """

    def _blank(m: re.Match[str]) -> str:
        token = m.group(0)
        # A literal collapses to an empty literal; a comment vanishes.
        if token.startswith(("'", '"')):
            return '""'
        return ""

    return _LITERAL_OR_COMMENT.sub(_blank, query)


# Block SERVICE keyword to prevent SSRF via federated queries.
_SERVICE_PATTERN = re.compile(r"\bSERVICE\b", re.IGNORECASE)

# ---- G1 (#844) result caps for LLM-authored queries --------------------
#
# Even a public-graph-only query can return tens of thousands of rows
# (e.g. ``SELECT ?s WHERE { ?s a estleg:EULegislation }`` over the 33k EU
# acts). Three independent guards keep a single tool call bounded:
#
#   * ``_QUERY_ONTOLOGY_ROW_CAP`` — hard ceiling on rows returned to the
#     LLM (the result list is truncated past this).
#   * ``_QUERY_ONTOLOGY_BYTE_CAP`` — ceiling on the serialised JSON size
#     so a few very wide rows can't blow the context window / token bill.
#   * an injected ``LIMIT`` — when the LLM omits one, we append a LIMIT so
#     Jena itself stops early rather than materialising a huge result.
_QUERY_ONTOLOGY_ROW_CAP = 200
_QUERY_ONTOLOGY_BYTE_CAP = 200_000  # ~200 KB of serialised JSON
_QUERY_ONTOLOGY_DEFAULT_LIMIT = 200

# Detect a top-level LIMIT so we don't double-append one. SPARQL allows a
# trailing ``LIMIT n [OFFSET m]``. The scan runs over the
# literal/comment-stripped query (see ``_strip_literals_and_comments``) so
# a ``LIMIT`` inside a quoted string or a ``#`` comment is NOT mistaken
# for a real clause — that asymmetry matters because LIMIT detection is an
# allow-list decision and a false positive would skip injection.
_LIMIT_PATTERN = re.compile(r"\bLIMIT\s+\d+", re.IGNORECASE)


def _enforce_query_limit(query: str, default_limit: int = _QUERY_ONTOLOGY_DEFAULT_LIMIT) -> str:
    """Append a ``LIMIT`` to a SELECT *query* when it has none (G1).

    Only SELECT is limited here — by the time this runs the form has
    already been narrowed to SELECT or ASK by :func:`_is_read_only_sparql`
    (DESCRIBE / CONSTRUCT are rejected). ASK yields a single boolean and
    needs no LIMIT, so it is returned unchanged.

    The "does it already have a LIMIT?" check is literal- and
    comment-aware: a ``LIMIT 5`` appearing inside a string literal or a
    ``#`` comment must NOT suppress injection, otherwise the query reaches
    Jena uncapped. We therefore scan a stripped copy of the query.
    """
    stripped = _strip_literals_and_comments(query)
    body = stripped.strip()
    # Strip leading PREFIX/BASE to find the query form.
    while True:
        m = re.match(r"(?i)\s*PREFIX\s+\S+:\s*<[^>]*>\s*", body)
        if m:
            body = body[m.end() :]
            continue
        m = re.match(r"(?i)\s*BASE\s*<[^>]*>\s*", body)
        if m:
            body = body[m.end() :]
            continue
        break
    body = body.lstrip()
    if not re.match(r"(?i)^SELECT\b", body):
        # ASK — LIMIT not applicable.
        return query
    if _LIMIT_PATTERN.search(stripped):
        return query
    return f"{query.rstrip()}\nLIMIT {default_limit}"


def _is_read_only_sparql(query: str) -> bool:
    """Return True if *query* is a safe, capable-of-being-capped query.

    Uses a whitelist approach:
    1. Strip comments (``#...`` to end of line).
    2. Strip leading PREFIX/BASE declarations.
    3. Verify the query body starts with SELECT or ASK. DESCRIBE and
       CONSTRUCT are rejected (#844 review): DESCRIBE can't be reliably
       LIMIT-bounded and invites whole-graph server-side materialisation;
       CONSTRUCT emits triples rather than the binding rows the executor's
       caps are built for.
    4. Block the SERVICE keyword anywhere (prevents SSRF via federated queries).
    """
    # Strip comments
    cleaned = _COMMENT_PATTERN.sub("", query)

    # Block SERVICE keyword anywhere in the query
    if _SERVICE_PATTERN.search(cleaned):
        return False

    # Strip leading whitespace and PREFIX/BASE declarations line by line
    body = cleaned.strip()
    while True:
        m = re.match(r"(?i)\s*PREFIX\s+\S+:\s*<[^>]*>\s*", body)
        if m:
            body = body[m.end() :]
            continue
        m = re.match(r"(?i)\s*BASE\s*<[^>]*>\s*", body)
        if m:
            body = body[m.end() :]
            continue
        break

    body = body.lstrip()

    # Verify the query starts with an allowed form
    return _ALLOWED_QUERY_FORMS.match(body) is not None


# ---------------------------------------------------------------------------
# Tool executors
# ---------------------------------------------------------------------------


async def _exec_query_ontology(
    tool_input: dict[str, Any],
    sparql: SparqlClient,
) -> dict[str, Any]:
    """Execute a read-only, public-graph-only, capped SPARQL query.

    Three security/safety gates (#844):

    1. :func:`_is_read_only_sparql` — accept only SELECT / ASK (reject
       mutations and the uncappable DESCRIBE / CONSTRUCT forms).
    2. :func:`app.ontology.scoping.assert_public_only` — reject any
       ``GRAPH`` / ``FROM`` / ``FROM NAMED`` keyword so the query can
       only touch the public default graph, never an org-private draft
       named graph (C1).
    3. result caps — inject a ``LIMIT`` when missing (literal/comment-aware
       detection), then truncate the returned rows to
       :data:`_QUERY_ONTOLOGY_ROW_CAP` and the serialised payload to
       :data:`_QUERY_ONTOLOGY_BYTE_CAP` (G1).
    """
    query = tool_input.get("query", "")
    if not query.strip():
        return {"error": "Empty SPARQL query"}

    if not _is_read_only_sparql(query):
        return {"error": "Only read-only SELECT or ASK SPARQL queries are allowed"}

    # C1: confine the LLM to the public default graph. Any GRAPH / FROM /
    # FROM NAMED keyword could reach an org-private draft named graph in
    # the shared dataset, so it is a hard reject.
    try:
        assert_public_only(query)
    except ValueError as exc:
        return {"error": str(exc)}

    # G1: make Jena stop early when the LLM forgot a LIMIT.
    capped_query = _enforce_query_limit(query)

    results = sparql.query(capped_query)

    # G1: defence in depth — even with the injected LIMIT, truncate the
    # row list and the serialised size before handing it to the model.
    truncated = False
    if len(results) > _QUERY_ONTOLOGY_ROW_CAP:
        results = results[:_QUERY_ONTOLOGY_ROW_CAP]
        truncated = True

    payload: dict[str, Any] = {"results": results}
    serialized = json.dumps(payload, ensure_ascii=False)
    if len(serialized.encode("utf-8")) > _QUERY_ONTOLOGY_BYTE_CAP:
        # Drop rows from the tail until we fit under the byte cap. A
        # linear shrink is fine — the row cap already bounds the worst
        # case at 200 rows.
        truncated = True
        while (
            results
            and len(json.dumps({"results": results}, ensure_ascii=False).encode("utf-8"))
            > _QUERY_ONTOLOGY_BYTE_CAP
        ):
            results = results[: max(1, len(results) // 2)]
            if len(results) == 1:
                break
        payload = {"results": results}

    if truncated:
        payload["truncated"] = True
        payload["row_cap"] = _QUERY_ONTOLOGY_ROW_CAP
    return payload


async def _exec_search_provisions(
    tool_input: dict[str, Any],
    sparql: SparqlClient,
) -> dict[str, Any]:
    """Search provisions by keyword using SPARQL FILTER(CONTAINS())."""
    keywords = tool_input.get("keywords", "")
    if not keywords.strip():
        return {"error": "Empty keywords"}

    limit = tool_input.get("limit", 10)
    if not isinstance(limit, int) or limit <= 0:
        limit = 10
    if limit > 100:
        limit = 100

    safe_keywords = _sanitize_sparql_value(keywords)

    query = f"""
        PREFIX estleg: <https://data.riik.ee/ontology/estleg#>
        PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

        SELECT ?uri ?paragrahv ?summary ?source_act
        WHERE {{
            ?uri estleg:paragrahv ?paragrahv .
            OPTIONAL {{ ?uri estleg:summary ?summary . }}
            OPTIONAL {{ ?uri estleg:sourceAct ?source_act . }}
            FILTER(
                CONTAINS(LCASE(STR(?paragrahv)), LCASE("{safe_keywords}"))
                || CONTAINS(LCASE(STR(?summary)), LCASE("{safe_keywords}"))
            )
        }}
        LIMIT {limit}
    """
    results = sparql.query(query)
    provisions = [
        {
            "uri": row.get("uri", ""),
            "paragrahv": row.get("paragrahv", ""),
            "summary": row.get("summary", ""),
            "source_act": row.get("source_act", ""),
        }
        for row in results
    ]
    return {"provisions": provisions}


async def _exec_get_draft_impact(
    tool_input: dict[str, Any],
    sparql: SparqlClient,
    auth: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Read the latest impact report for a given draft from the DB.

    The query joins with the ``drafts`` table and filters by the
    caller's ``org_id`` to prevent cross-organisation data access.
    """
    draft_id = tool_input.get("draft_id", "")
    if not draft_id.strip():
        return {"error": "Empty draft_id"}

    # M3: validate draft_id is a proper UUID
    try:
        UUID(draft_id)
    except (ValueError, TypeError):
        return {"error": "Invalid draft_id format"}

    # H2: org-scoping — require auth with org_id
    org_id: str | None = None
    if auth:
        org_id = auth.get("org_id")

    if not org_id:
        return {"error": "Authentication with org_id required"}

    try:
        with get_connection() as conn:
            row = conn.execute(
                """
                SELECT ir.report_data
                FROM impact_reports ir
                JOIN drafts d ON d.id = ir.draft_id
                WHERE ir.draft_id = %s AND d.org_id = %s
                ORDER BY ir.generated_at DESC
                LIMIT 1
                """,
                (draft_id, org_id),
            ).fetchone()
    except Exception:
        logger.exception("Failed to fetch impact report for draft_id=%s", draft_id)
        return {"error": "Failed to read impact report from database"}

    if row is None:
        return {"error": f"No impact report found for draft {draft_id}"}

    report_data = row[0]
    if isinstance(report_data, str):
        try:
            report_data = json.loads(report_data)
        except json.JSONDecodeError:
            pass

    return {"report": report_data}


async def _exec_get_provision_details(
    tool_input: dict[str, Any],
    sparql: SparqlClient,
) -> dict[str, Any]:
    """SPARQL query for detailed information about a single provision."""
    provision_uri = tool_input.get("provision_uri", "")
    if not provision_uri.strip():
        return {"error": "Empty provision_uri"}

    # Strict URI validation — reject anything that doesn't match known-safe
    # patterns.  _sanitize_sparql_value only escapes string-literal chars and
    # is NOT safe for URI contexts (angle brackets, braces, spaces, etc.).
    if provision_uri.startswith("estleg:"):
        if not _SAFE_PREFIXED_RE.fullmatch(provision_uri):
            return {
                "error": (
                    "Invalid prefixed URI. Only alphanumeric characters, "
                    "underscores, and hyphens are allowed after 'estleg:'."
                )
            }
        uri_ref = provision_uri  # keep as prefixed name
        filter_clause = f"BIND({uri_ref} AS ?uri)"
    elif _SAFE_FULL_URI_RE.fullmatch(provision_uri):
        filter_clause = f"BIND(<{provision_uri}> AS ?uri)"
    else:
        return {
            "error": (
                "Invalid provision URI. Must be a prefixed name "
                "(estleg:...) or a valid http(s) URI."
            )
        }

    # C0 (2026-05-15): the legacy ``estleg:relatedTo`` predicate does not
    # exist in the source ontology — the audit (plan doc section 2.5)
    # confirmed it always returned zero rows. The "related" list is now
    # populated from the three canonical "is meaningfully connected"
    # predicates: ``references``, ``semanticallySimilarTo``, and
    # ``harmonisedWith``. Each row's ``?relation`` projection lets the
    # caller render the relation type in legal language.
    query = f"""
        PREFIX estleg: <https://data.riik.ee/ontology/estleg#>
        PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

        SELECT ?uri ?text ?sourceAct ?paragrahv ?related ?relLabel ?relation
        WHERE {{
            {filter_clause}
            OPTIONAL {{ ?uri estleg:text ?text . }}
            OPTIONAL {{ ?uri estleg:sourceAct ?sourceAct . }}
            OPTIONAL {{ ?uri estleg:paragrahv ?paragrahv . }}
            OPTIONAL {{
                {{
                    ?uri estleg:references ?related .
                    BIND(estleg:references AS ?relation)
                }} UNION {{
                    ?uri estleg:semanticallySimilarTo ?related .
                    BIND(estleg:semanticallySimilarTo AS ?relation)
                }} UNION {{
                    ?uri estleg:harmonisedWith ?related .
                    BIND(estleg:harmonisedWith AS ?relation)
                }}
                OPTIONAL {{ ?related rdfs:label ?relLabel . }}
            }}
        }}
    """
    results = sparql.query(query)

    if not results:
        return {"error": f"Provision not found: {provision_uri}"}

    first = results[0]
    related_list = []
    seen_related: set[str] = set()
    for row in results:
        rel = row.get("related", "")
        if rel and rel not in seen_related:
            seen_related.add(rel)
            related_list.append(
                {
                    "uri": rel,
                    "label": row.get("relLabel", ""),
                    "relation": row.get("relation", ""),
                }
            )

    return {
        "provision": {
            "uri": first.get("uri", provision_uri),
            "text": first.get("text", ""),
            "source_act": first.get("sourceAct", ""),
            "paragrahv": first.get("paragrahv", ""),
            "related": related_list,
        }
    }


# ---------------------------------------------------------------------------
# C4 specialised helpers — shared infrastructure
# ---------------------------------------------------------------------------
#
# Each of the four helpers below performs the same opening dance:
#
#   1. Validate the ``provision_uri`` parameter against
#      ``_SAFE_PREFIXED_RE`` / ``_SAFE_FULL_URI_RE`` (same allowlist as
#      :func:`_exec_get_provision_details` — prevents SPARQL injection).
#   2. Clamp the optional ``limit`` to ``1..100``.
#   3. Build a ``BIND(...)`` clause that materialises the validated URI
#      as ``?uri`` so the rest of the template can use it without further
#      escaping.
#
# Sharing :func:`_resolve_provision_binding` lets the executors stay focused
# on their query shape and keeps the security-critical validation in one
# auditable function. Every executor projects ``?source`` (the URI of the
# row that *originated* the relation) so the LLM can cite back to the
# specific provision / amendment event / EU act, never just a label.


_DEFAULT_PROVISION_LIMIT = 25
_MAX_PROVISION_LIMIT = 100


def _resolve_provision_binding(
    tool_input: dict[str, Any],
    *,
    default_limit: int = _DEFAULT_PROVISION_LIMIT,
) -> tuple[str, int] | dict[str, Any]:
    """Validate ``provision_uri`` + ``limit`` from a tool input.

    Returns either a ``(bind_clause, limit)`` tuple ready to drop into a
    SPARQL template, or an ``{"error": ...}`` dict that the caller should
    return verbatim. Mirroring the pattern of
    :func:`_exec_get_provision_details` lets us reject the same shapes of
    bad input across every C4 helper.
    """
    provision_uri = tool_input.get("provision_uri", "")
    if not isinstance(provision_uri, str) or not provision_uri.strip():
        return {"error": "Empty provision_uri"}

    if provision_uri.startswith("estleg:"):
        if not _SAFE_PREFIXED_RE.fullmatch(provision_uri):
            return {
                "error": (
                    "Invalid prefixed URI. Only alphanumeric characters, "
                    "underscores, and hyphens are allowed after 'estleg:'."
                )
            }
        bind_clause = f"BIND({provision_uri} AS ?uri)"
    elif _SAFE_FULL_URI_RE.fullmatch(provision_uri):
        bind_clause = f"BIND(<{provision_uri}> AS ?uri)"
    else:
        return {
            "error": (
                "Invalid provision URI. Must be a prefixed name "
                "(estleg:...) or a valid http(s) URI."
            )
        }

    raw_limit = tool_input.get("limit", default_limit)
    if not isinstance(raw_limit, int) or raw_limit <= 0:
        limit = default_limit
    else:
        limit = min(raw_limit, _MAX_PROVISION_LIMIT)

    return bind_clause, limit


# ---------------------------------------------------------------------------
# C4 #1 — court decisions interpreting a provision
# ---------------------------------------------------------------------------


async def _exec_get_court_decisions_for_provision(
    tool_input: dict[str, Any],
    sparql: SparqlClient,
) -> dict[str, Any]:
    """Return court decisions interpreting *provision_uri*.

    Walks both ``CourtDecision interpretsLaw Provision`` (forward) and
    ``Provision interpretedBy CourtDecision`` (inverse) so the result is
    insensitive to which direction the data was loaded in. The optional
    ``validFrom`` / ``caseNumber`` projections give the LLM something to
    cite even when ``rdfs:label`` is missing.
    """
    resolved = _resolve_provision_binding(tool_input)
    if isinstance(resolved, dict):
        return resolved
    bind_clause, limit = resolved

    query = f"""
        PREFIX estleg: <https://data.riik.ee/ontology/estleg#>
        PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

        SELECT DISTINCT ?decision ?label ?caseNumber ?date ?relation ?source WHERE {{
            {bind_clause}
            {{
                ?decision <{PREDICATES.INTERPRETS_LAW}> ?uri .
                BIND(<{PREDICATES.INTERPRETS_LAW}> AS ?relation)
            }} UNION {{
                ?uri <{PREDICATES.INTERPRETED_BY}> ?decision .
                BIND(<{PREDICATES.INTERPRETED_BY}> AS ?relation)
            }}
            OPTIONAL {{ ?decision rdfs:label ?label }}
            OPTIONAL {{ ?decision estleg:caseNumber ?caseNumber }}
            OPTIONAL {{ ?decision estleg:validFrom ?date }}
            BIND(?uri AS ?source)
        }}
        ORDER BY DESC(?date) ?decision
        LIMIT {limit}
    """
    results = sparql.query(query)
    decisions = [
        {
            "uri": row.get("decision", ""),
            "label": row.get("label", ""),
            "case_number": row.get("caseNumber", ""),
            "date": row.get("date", ""),
            "relation": row.get("relation", ""),
            "source": row.get("source", ""),
        }
        for row in results
    ]
    return {"decisions": decisions, "count": len(decisions)}


# ---------------------------------------------------------------------------
# C4 #2 — EU transposition links for a provision
# ---------------------------------------------------------------------------


async def _exec_get_eu_transposition_for_provision(
    tool_input: dict[str, Any],
    sparql: SparqlClient,
) -> dict[str, Any]:
    """Return EU acts linked to *provision_uri* via transposition / harmonisation.

    Three UNION arms cover the canonical edges:

    1. Provision-level ``transposesDirective`` (SHACL allows it).
    2. Provision-level ``harmonisedWith``.
    3. Inverse ``transposedBy`` from the EU side.

    The query also projects the raw ``estleg:transpositionStatus`` literal
    where it exists so the caller can render the official status word
    ("ülevõetud", "osaliselt", …) without re-querying.
    """
    resolved = _resolve_provision_binding(tool_input)
    if isinstance(resolved, dict):
        return resolved
    bind_clause, limit = resolved

    query = f"""
        PREFIX estleg: <https://data.riik.ee/ontology/estleg#>
        PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

        SELECT DISTINCT ?euAct ?label ?celex ?status ?relation ?source WHERE {{
            {bind_clause}
            {{
                ?uri <{PREDICATES.TRANSPOSES_DIRECTIVE}> ?euAct .
                BIND(<{PREDICATES.TRANSPOSES_DIRECTIVE}> AS ?relation)
                BIND(?uri AS ?source)
            }} UNION {{
                ?uri <{PREDICATES.HARMONISED_WITH}> ?euAct .
                BIND(<{PREDICATES.HARMONISED_WITH}> AS ?relation)
                BIND(?uri AS ?source)
            }} UNION {{
                ?euAct <{PREDICATES.TRANSPOSED_BY}> ?uri .
                BIND(<{PREDICATES.TRANSPOSED_BY}> AS ?relation)
                BIND(?uri AS ?source)
            }}
            OPTIONAL {{ ?euAct rdfs:label ?label }}
            OPTIONAL {{ ?euAct estleg:celexNumber ?celex }}
            OPTIONAL {{ ?source estleg:transpositionStatus ?status }}
        }}
        ORDER BY ?euAct
        LIMIT {limit}
    """
    results = sparql.query(query)
    eu_acts = [
        {
            "uri": row.get("euAct", ""),
            "label": row.get("label", ""),
            "celex": row.get("celex", ""),
            "status": row.get("status", ""),
            "relation": row.get("relation", ""),
            "source": row.get("source", ""),
        }
        for row in results
    ]
    return {"eu_acts": eu_acts, "count": len(eu_acts)}


# ---------------------------------------------------------------------------
# C4 #3 — amendment history for a provision
# ---------------------------------------------------------------------------


async def _exec_get_provision_amendments(
    tool_input: dict[str, Any],
    sparql: SparqlClient,
) -> dict[str, Any]:
    """Return the ordered amendment history for *provision_uri*.

    Two relation shapes are unioned:

    * ``AmendmentEvent estleg:amends Provision`` (forward — the canonical
      direction; the AmendmentEvent's ``validFrom`` is the date the
      amendment took effect).
    * ``Provision estleg:amendedBy Act/Draft`` (inverse — older data and
      some draft chains record it this way).

    Rows are ordered by ``validFrom DESC`` (most recent first); rows with
    no date sort last so a partial dataset still produces a stable order.
    """
    resolved = _resolve_provision_binding(tool_input, default_limit=50)
    if isinstance(resolved, dict):
        return resolved
    bind_clause, limit = resolved

    query = f"""
        PREFIX estleg: <https://data.riik.ee/ontology/estleg#>
        PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

        SELECT DISTINCT ?amendment ?label ?date ?relation ?source WHERE {{
            {bind_clause}
            {{
                ?amendment <{PREDICATES.AMENDS}> ?uri .
                BIND(<{PREDICATES.AMENDS}> AS ?relation)
            }} UNION {{
                ?uri <{PREDICATES.AMENDED_BY}> ?amendment .
                BIND(<{PREDICATES.AMENDED_BY}> AS ?relation)
            }}
            OPTIONAL {{ ?amendment rdfs:label ?label }}
            OPTIONAL {{ ?amendment estleg:validFrom ?date }}
            BIND(?uri AS ?source)
        }}
        ORDER BY DESC(?date) ?amendment
        LIMIT {limit}
    """
    results = sparql.query(query)
    amendments = [
        {
            "uri": row.get("amendment", ""),
            "label": row.get("label", ""),
            "date": row.get("date", ""),
            "relation": row.get("relation", ""),
            "source": row.get("source", ""),
        }
        for row in results
    ]
    return {"amendments": amendments, "count": len(amendments)}


# ---------------------------------------------------------------------------
# C4 #4 — related concepts and topic clusters
# ---------------------------------------------------------------------------


async def _exec_get_related_concepts(
    tool_input: dict[str, Any],
    sparql: SparqlClient,
) -> dict[str, Any]:
    """Return defined concepts + topic clusters for *provision_uri*.

    Three UNION arms:

    1. ``definesConcept`` — the canonical LegalProvision -> LegalConcept link.
    2. ``requestedCluster`` — the populated provision -> topic cluster link.
    3. ``topicCluster`` — the SHACL alias; mostly empty today but queried
       so callers don't need to repeat the rollout once the data migrates.

    Each row exposes ``?kind`` (``"concept"`` or ``"cluster"``) so a
    renderer can group without re-parsing the relation URI.
    """
    resolved = _resolve_provision_binding(tool_input)
    if isinstance(resolved, dict):
        return resolved
    bind_clause, limit = resolved

    query = f"""
        PREFIX estleg: <https://data.riik.ee/ontology/estleg#>
        PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

        SELECT DISTINCT ?related ?label ?relation ?kind ?source WHERE {{
            {bind_clause}
            {{
                ?uri <{PREDICATES.DEFINES_CONCEPT}> ?related .
                BIND(<{PREDICATES.DEFINES_CONCEPT}> AS ?relation)
                BIND("concept" AS ?kind)
            }} UNION {{
                ?uri <{PREDICATES.REQUESTED_CLUSTER}> ?related .
                BIND(<{PREDICATES.REQUESTED_CLUSTER}> AS ?relation)
                BIND("cluster" AS ?kind)
            }} UNION {{
                ?uri <{PREDICATES.TOPIC_CLUSTER}> ?related .
                BIND(<{PREDICATES.TOPIC_CLUSTER}> AS ?relation)
                BIND("cluster" AS ?kind)
            }}
            OPTIONAL {{ ?related rdfs:label ?label }}
            BIND(?uri AS ?source)
        }}
        ORDER BY ?kind ?related
        LIMIT {limit}
    """
    results = sparql.query(query)
    related = [
        {
            "uri": row.get("related", ""),
            "label": row.get("label", ""),
            "relation": row.get("relation", ""),
            "kind": row.get("kind", ""),
            "source": row.get("source", ""),
        }
        for row in results
    ]
    return {"related": related, "count": len(related)}


# ---------------------------------------------------------------------------
# Executor dispatcher
# ---------------------------------------------------------------------------

_EXECUTORS: dict[str, Any] = {
    "query_ontology": _exec_query_ontology,
    "search_provisions": _exec_search_provisions,
    "get_draft_impact": _exec_get_draft_impact,
    "get_provision_details": _exec_get_provision_details,
    # C4 specialised helpers (2026-05-16).
    "get_court_decisions_for_provision": _exec_get_court_decisions_for_provision,
    "get_eu_transposition_for_provision": _exec_get_eu_transposition_for_provision,
    "get_provision_amendments": _exec_get_provision_amendments,
    "get_related_concepts": _exec_get_related_concepts,
}


async def execute_tool(
    tool_name: str,
    tool_input: dict[str, Any],
    sparql: SparqlClient,
    auth: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Dispatch a tool call to the appropriate executor.

    Returns a dict with either the tool's results or an ``"error"`` key.
    Executor exceptions are caught and returned as error dicts (never crash).

    Parameters
    ----------
    auth:
        Auth dict from the caller (must have ``org_id`` for tools that
        require org-scoping, e.g. ``get_draft_impact``).
    """
    fn = _EXECUTORS.get(tool_name)
    if fn is None:
        return {"error": f"Unknown tool: {tool_name}"}
    try:
        # Thread auth to executors that accept it.
        import inspect

        sig = inspect.signature(fn)
        if "auth" in sig.parameters:
            return await fn(tool_input, sparql, auth=auth)
        return await fn(tool_input, sparql)
    except Exception as e:
        logger.exception("Tool %s failed", tool_name)
        return {"error": str(e)[:200]}
