-- =============================================================================
-- Migration 021: Mask leaked environment errors in drafts.error_message (#656)
-- =============================================================================
--
-- Historical drafts that failed before ``app.docs.error_mapping`` was
-- wired up into every handler wrote raw exception strings into
-- ``drafts.error_message``. Some of those strings leak environment
-- variable names and deployment-mode details directly to end users,
-- e.g.:
--
--     "ANTHROPIC_API_KEY must be set when APP_ENV=production"
--
-- Ministry lawyers have no way to act on such a message, and it leaks
-- operational internals that do not belong in the UI.
--
-- This migration rewrites every matching historical row so that:
--
--   * ``drafts.error_debug`` preserves the original technical string
--     (only when ``error_debug`` is currently NULL, so we never
--     clobber a better debug value that a later retry may have
--     written).
--   * ``drafts.error_message`` is replaced with the canonical Estonian
--     fallback string produced by
--     ``app.docs.error_mapping.MSG_UNKNOWN``.
--
-- The fallback string is hardcoded here rather than loaded from Python
-- because migrations run before any application code. The two MUST
-- stay in sync; if :data:`app.docs.error_mapping.MSG_UNKNOWN` ever
-- changes, update this migration's comment and add a follow-up
-- migration — do NOT edit this file after it has been applied.
--
-- Revert
-- ------
--
-- There is no DOWN migration. The original message is preserved in
-- ``error_debug`` so the change is non-destructive — an operator can
-- always recover the original text with:
--
--     SELECT id, error_debug FROM drafts
--     WHERE error_debug IS NOT NULL AND status = 'failed';
--
-- If a revert is genuinely required, the original message can be
-- copied back out of ``error_debug`` with a one-off UPDATE, but the
-- leaked-env rows are the whole point of this migration so that would
-- defeat it.
--
-- Idempotency
-- -----------
--
-- Safe to re-run: the WHERE clause filters out rows whose
-- ``error_message`` has already been replaced with the canonical
-- fallback. Any future failures that produce a leaked-env message will
-- be caught by error_mapping.py and will never reach this migration.
-- =============================================================================

-- Step 1: preserve the original raw message in error_debug for admin
-- triage. Only populate error_debug when it's currently NULL so we
-- never clobber a richer debug string that a later run might have
-- produced.
UPDATE drafts
SET error_debug = error_message
WHERE error_debug IS NULL
  AND error_message IS NOT NULL
  AND (
    error_message LIKE '%ANTHROPIC_API_KEY%'
    OR error_message LIKE '%STORAGE_ENCRYPTION_KEY%'
    OR error_message LIKE '%TIKA_URL%'
    OR error_message LIKE '%APP_ENV=%'
    OR error_message LIKE '%VOYAGE_API_KEY%'
  );

-- Step 2: replace the user-facing message with the canonical Estonian
-- fallback string. Must match MSG_UNKNOWN in
-- app/docs/error_mapping.py exactly.
UPDATE drafts
SET error_message = 'Töötlemine ebaõnnestus tehnilisel põhjusel. Meeskond on teavitatud.',
    updated_at = now()
WHERE error_message IS NOT NULL
  AND error_message != 'Töötlemine ebaõnnestus tehnilisel põhjusel. Meeskond on teavitatud.'
  AND (
    error_message LIKE '%ANTHROPIC_API_KEY%'
    OR error_message LIKE '%STORAGE_ENCRYPTION_KEY%'
    OR error_message LIKE '%TIKA_URL%'
    OR error_message LIKE '%APP_ENV=%'
    OR error_message LIKE '%VOYAGE_API_KEY%'
  );
