"""Analüüsikeskus routes package (#860).

The Analüüsikeskus is the legal-analysis workflow hub — design rationale in
``docs/2026-05-11-ministry-lawyer-ui-structure.md``. This package registers
**eleven** workflows (was a single 6.9k-line ``routes.py`` module; split
per-workflow in #860, mirroring the ``app/docs/routes/`` precedent):

    GET  /analyysikeskus                       — directory (#720)        [_directory]
    GET  /analyysikeskus/normi-mojuahel        — Normi mõjuahel (#722)    [_normi]
    GET  /analyysikeskus/el-ulevott            — EL ülevõtt (#723)        [_el_ulevott]
    GET  /analyysikeskus/sanktsioonid          — Sanktsioonide indeks     [_sanktsioonid]
    GET  /analyysikeskus/kohtupraktika         — Kohtupraktika            [_kohtupraktika]
    GET  /analyysikeskus/halduskoormus         — Halduskoormus            [_halduskoormus]
    GET  /analyysikeskus/padevused             — Pädevused                [_padevused]
    GET  /analyysikeskus/ajalugu               — Ajalugu                  [_ajalugu]
    GET  /analyysikeskus/sarnasus              — Sarnasus                 [_sarnasus]
    GET  /analyysikeskus/moju-poliitikamottest — Mõju poliitikamõttest    [_intent] (#814)
    POST .../moju-poliitikamottest/extract     — candidate extraction     [_intent]
    POST .../moju-poliitikamottest/analyze     — aggregated impact run    [_intent]

Auth is handled by the global ``auth_before`` middleware — none of these
paths are in ``SKIP_PATHS``, so an unauthenticated request is redirected to
``/auth/login`` before any handler runs.

Cross-workflow helpers (the ``_Scope`` model, the ``Ulatus`` scope-form
builder, the impact-result rendering machinery shared by Normi + the
policy-intent flow, and the reference-resolution helpers) live in
``_common``. Each workflow submodule imports what it needs from ``_common``
and composes the existing engine modules
(``adhoc_analysis`` / ``eu_transposition`` / ``sanctions`` / … — unchanged).

For framework-free service functions (the Phase-5 REST/MCP reference
pattern) see ``app/analyysikeskus/services/`` and
``docs/2026-06-12-service-layer-convention.md``.

Every public name is re-exported here so existing direct imports
(``from app.analyysikeskus.routes import _Scope`` /
``from app.analyysikeskus.routes import _ANALYYSIKESKUS_INPUTS``) keep
working.

**Patch-path caveat (post-#860):** ``patch("app.analyysikeskus.routes.X")``
rebinds the symbol in THIS package\'s namespace only. Submodules import
their dependencies at module load time, so a package-level patch does NOT
propagate into a submodule\'s call sites. To intercept a submodule
dependency, patch where it is USED (e.g.
``patch("app.analyysikeskus.routes._sanktsioonid.list_sanctions_for_provision")``
or ``patch("app.analyysikeskus.routes._normi.run_adhoc_impact_analysis")``).
This is the standard "patch where used" rule, pinned by
``tests/test_analyysikeskus_routes_patch_paths.py``.
"""

from __future__ import annotations

from app.analyysikeskus.routes._ajalugu import (
    _AJALUGU_V1_BANNER_BODY_ET,
    _AJALUGU_V1_BANNER_HEADING_ET,
    _AJALUGU_V1_BANNER_ISSUE_URL,
    _WORKFLOW_AJALUGU,
    _ajalugu_act_timeline_items,
    _ajalugu_actions,
    _ajalugu_amendment_items,
    _ajalugu_court_items,
    _ajalugu_evidence_block,
    _ajalugu_impact_items,
    _ajalugu_input_type,
    _ajalugu_link,
    _ajalugu_pending_items,
    _ajalugu_results_block,
    _ajalugu_scope_block,
    _ajalugu_timeline_section,
    _ajalugu_v1_banner,
    _fmt_date_et,
    _is_ajalugu_provision_input,
    _render_ajalugu_disambiguation,
    _render_ajalugu_landing,
    _render_ajalugu_result,
    _render_ajalugu_unresolved,
    ajalugu_page,
)
from app.analyysikeskus.routes._common import (
    _CELEX_TOKEN_RE,
    _COURT_TYPE_LOCALNAMES,
    _DRAFT_TYPE_LOCALNAMES,
    _EVIDENCE_SEED_MAX_LEN,
    _LAW_SCOPE_OPTIONS,
    _MAX_RAG_CANDIDATES,
    _MAX_RECENT_ANALYSES,
    _MAX_RESULT_ROWS,
    _RISK_BAND_BADGE_VARIANT,
    _RISK_BAND_LABELS_ET,
    _TEMPORAL_SCOPE_OPTIONS,
    _WORKFLOW_ACTION,
    _WORKFLOW_EL,
    _WORKFLOW_NORMI,
    _build_evidence_block,
    _build_results_block,
    _el_seosed_section,
    _entity_display_label,
    _entity_link,
    _evidence_row,
    _evidence_seed_form,
    _evidence_seed_text,
    _has_resolved_target,
    _is_court_conflict,
    _is_provision_resolved,
    _korge_riskiga_section,
    _missing_row,
    _partial_act_title,
    _peamised_mojud_section,
    _rag_candidates,
    _resolve_refs,
    _resolved_key,
    _resolved_label,
    _resolved_type_label,
    _riigikohtu_section,
    _risk_and_recommendation,
    _sanctions_link,
    _Scope,
    _scope_form,
    _select_dispatchable,
    _seotud_eelnoud_section,
    _split_link_query,
    _sub_section,
    _temporal_scope_select,
    _try_parse_uuid,
    _type_label,
    _type_localname,
    _workflow_link,
)
from app.analyysikeskus.routes._directory import (
    _ANALYYSIKESKUS_INPUTS,
    _capability_card,
    _get_recent_analyses,
    _intent_workflow_card,
    _planned_workflow_card,
    _recent_analyses_card,
    _step_label,
    _workflow_card,
    analyysikeskus_page,
)
from app.analyysikeskus.routes._el_ulevott import (
    _TRANSPOSITION_RELATION_ET,
    _TRANSPOSITION_STATUS_ACTION_ET,
    _TRANSPOSITION_STATUS_BADGE,
    _TRANSPOSITION_STATUS_LABEL_ET,
    _ee_act_cell,
    _ee_provision_cell,
    _el_ulevott_scope_block,
    _eu_act_cell,
    _eu_actions,
    _eu_celex_or_label,
    _eu_evidence_block,
    _eu_input_summary,
    _eu_link,
    _eu_recommendation,
    _eu_results_block,
    _eu_risk_band,
    _eu_summary_line,
    _render_eu_disambiguation,
    _render_eu_transposition_result,
    _render_eu_unresolved,
    _status_action_cell,
    _status_badge_cell,
    el_ulevott_page,
)
from app.analyysikeskus.routes._halduskoormus import (
    _MAX_BURDEN_DISPLAY_ROWS,
    _WORKFLOW_BURDEN,
    _burden_actions,
    _burden_count_grid,
    _burden_delta_block,
    _burden_duty_holder_section,
    _burden_evidence_block,
    _burden_link,
    _burden_per_bucket_table,
    _burden_results_block,
    _burden_scope_block,
    _burden_summary_line,
    _is_draft_resolved,
    _render_burden_disambiguation,
    _render_burden_landing,
    _render_burden_result,
    _render_burden_unresolved,
    halduskoormus_page,
)
from app.analyysikeskus.routes._intent import (
    _INTENT_CONFIDENCE_PRE_CHECK,
    _INTENT_RESULT_REGION_ID,
    _MAX_INTENT_CANDIDATES,
    _MAX_INTENT_CONFIRMED_URIS,
    _MAX_INTENT_KNOWN_REFS,
    _MAX_INTENT_LEN,
    _intent_back_link,
    _intent_candidate_row,
    _intent_chip_group,
    _intent_chip_summary,
    _intent_confirmation_panel,
    _intent_empty_state,
    _intent_evidence_block,
    _intent_intake_form,
    _intent_intake_page,
    _intent_per_uri_section,
    _intent_result_actions,
    _intent_result_input_summary,
    _intent_result_region,
    _intent_results_block,
    _intent_row_label,
    moju_poliitikamottest_analyze,
    moju_poliitikamottest_extract,
    moju_poliitikamottest_page,
)
from app.analyysikeskus.routes._kohtupraktika import (
    _WORKFLOW_KOHTUPRAKTIKA,
    _court_practice_actions,
    _court_practice_evidence_block,
    _court_practice_group_section,
    _court_practice_results_block,
    _court_practice_summary_line,
    _format_decision_label,
    _format_year_trend,
    _is_court_practice_provision,
    _kohtupraktika_link,
    _kohtupraktika_scope_block,
    _render_court_practice_disambiguation,
    _render_court_practice_landing,
    _render_court_practice_result,
    _render_court_practice_unresolved,
    kohtupraktika_page,
)
from app.analyysikeskus.routes._normi import (
    _candidate_links,
    _normi_link,
    _normi_scope_block,
    _render_adhoc_result,
    _render_disambiguation,
    _render_draft_backed_result,
    _render_unresolved,
    _result_actions,
    normi_mojuahel_page,
)
from app.analyysikeskus.routes._padevused import (
    _PADEVUSED_ORPHAN_BUCKET_LABEL,
    _WORKFLOW_PADEVUSED,
    _padevused_act_heading,
    _padevused_act_table,
    _padevused_actions,
    _padevused_evidence_block,
    _padevused_link,
    _padevused_overlaps_section,
    _padevused_results_block,
    _padevused_scope_block,
    _padevused_summary_line,
    _padevused_v2_banner,
    _render_padevused_disambiguation,
    _render_padevused_landing,
    _render_padevused_result,
    _render_padevused_unresolved,
    padevused_page,
)
from app.analyysikeskus.routes._sanktsioonid import (
    _SANCTION_ROW_KEY,
    _WORKFLOW_SANCTIONS,
    _fmt_amount,
    _render_sanctions_disambiguation,
    _render_sanctions_landing,
    _render_sanctions_result,
    _render_sanctions_unresolved,
    _sanction_act_cell,
    _sanction_default_cell,
    _sanction_enforcement_cell,
    _sanction_penalty_cell,
    _sanction_penalty_phrase,
    _sanction_provision_cell,
    _sanction_results_block,
    _sanction_summary_line,
    _sanction_type_cell,
    _sanctions_actions,
    _sanctions_evidence_block,
    _sanctions_scope_block,
    _sr,
    sanktsioonid_page,
)
from app.analyysikeskus.routes._sarnasus import (
    _SIMILARITY_REASON_VARIANTS,
    _WORKFLOW_SIMILARITY,
    _render_similarity_disambiguation,
    _render_similarity_landing,
    _render_similarity_result,
    _similarity_actions,
    _similarity_evidence_block,
    _similarity_link,
    _similarity_reason_badges,
    _similarity_results_block,
    _similarity_row_link,
    sarnasus_page,
)

__all__ = [
    "_AJALUGU_V1_BANNER_BODY_ET",
    "_AJALUGU_V1_BANNER_HEADING_ET",
    "_AJALUGU_V1_BANNER_ISSUE_URL",
    "_ANALYYSIKESKUS_INPUTS",
    "_CELEX_TOKEN_RE",
    "_COURT_TYPE_LOCALNAMES",
    "_DRAFT_TYPE_LOCALNAMES",
    "_EVIDENCE_SEED_MAX_LEN",
    "_INTENT_CONFIDENCE_PRE_CHECK",
    "_INTENT_RESULT_REGION_ID",
    "_LAW_SCOPE_OPTIONS",
    "_MAX_BURDEN_DISPLAY_ROWS",
    "_MAX_INTENT_CANDIDATES",
    "_MAX_INTENT_CONFIRMED_URIS",
    "_MAX_INTENT_KNOWN_REFS",
    "_MAX_INTENT_LEN",
    "_MAX_RAG_CANDIDATES",
    "_MAX_RECENT_ANALYSES",
    "_MAX_RESULT_ROWS",
    "_PADEVUSED_ORPHAN_BUCKET_LABEL",
    "_RISK_BAND_BADGE_VARIANT",
    "_RISK_BAND_LABELS_ET",
    "_SANCTION_ROW_KEY",
    "_SIMILARITY_REASON_VARIANTS",
    "_Scope",
    "_TEMPORAL_SCOPE_OPTIONS",
    "_TRANSPOSITION_RELATION_ET",
    "_TRANSPOSITION_STATUS_ACTION_ET",
    "_TRANSPOSITION_STATUS_BADGE",
    "_TRANSPOSITION_STATUS_LABEL_ET",
    "_WORKFLOW_ACTION",
    "_WORKFLOW_AJALUGU",
    "_WORKFLOW_BURDEN",
    "_WORKFLOW_EL",
    "_WORKFLOW_KOHTUPRAKTIKA",
    "_WORKFLOW_NORMI",
    "_WORKFLOW_PADEVUSED",
    "_WORKFLOW_SANCTIONS",
    "_WORKFLOW_SIMILARITY",
    "_ajalugu_act_timeline_items",
    "_ajalugu_actions",
    "_ajalugu_amendment_items",
    "_ajalugu_court_items",
    "_ajalugu_evidence_block",
    "_ajalugu_impact_items",
    "_ajalugu_input_type",
    "_ajalugu_link",
    "_ajalugu_pending_items",
    "_ajalugu_results_block",
    "_ajalugu_scope_block",
    "_ajalugu_timeline_section",
    "_ajalugu_v1_banner",
    "_build_evidence_block",
    "_build_results_block",
    "_burden_actions",
    "_burden_count_grid",
    "_burden_delta_block",
    "_burden_duty_holder_section",
    "_burden_evidence_block",
    "_burden_link",
    "_burden_per_bucket_table",
    "_burden_results_block",
    "_burden_scope_block",
    "_burden_summary_line",
    "_candidate_links",
    "_capability_card",
    "_court_practice_actions",
    "_court_practice_evidence_block",
    "_court_practice_group_section",
    "_court_practice_results_block",
    "_court_practice_summary_line",
    "_ee_act_cell",
    "_ee_provision_cell",
    "_el_seosed_section",
    "_el_ulevott_scope_block",
    "_entity_display_label",
    "_entity_link",
    "_eu_act_cell",
    "_eu_actions",
    "_eu_celex_or_label",
    "_eu_evidence_block",
    "_eu_input_summary",
    "_eu_link",
    "_eu_recommendation",
    "_eu_results_block",
    "_eu_risk_band",
    "_eu_summary_line",
    "_evidence_row",
    "_evidence_seed_form",
    "_evidence_seed_text",
    "_fmt_amount",
    "_fmt_date_et",
    "_format_decision_label",
    "_format_year_trend",
    "_get_recent_analyses",
    "_has_resolved_target",
    "_intent_back_link",
    "_intent_candidate_row",
    "_intent_chip_group",
    "_intent_chip_summary",
    "_intent_confirmation_panel",
    "_intent_empty_state",
    "_intent_evidence_block",
    "_intent_intake_form",
    "_intent_intake_page",
    "_intent_per_uri_section",
    "_intent_result_actions",
    "_intent_result_input_summary",
    "_intent_result_region",
    "_intent_results_block",
    "_intent_row_label",
    "_intent_workflow_card",
    "_is_ajalugu_provision_input",
    "_is_court_conflict",
    "_is_court_practice_provision",
    "_is_draft_resolved",
    "_is_provision_resolved",
    "_kohtupraktika_link",
    "_kohtupraktika_scope_block",
    "_korge_riskiga_section",
    "_missing_row",
    "_normi_link",
    "_normi_scope_block",
    "_padevused_act_heading",
    "_padevused_act_table",
    "_padevused_actions",
    "_padevused_evidence_block",
    "_padevused_link",
    "_padevused_overlaps_section",
    "_padevused_results_block",
    "_padevused_scope_block",
    "_padevused_summary_line",
    "_padevused_v2_banner",
    "_partial_act_title",
    "_peamised_mojud_section",
    "_planned_workflow_card",
    "_rag_candidates",
    "_recent_analyses_card",
    "_render_adhoc_result",
    "_render_ajalugu_disambiguation",
    "_render_ajalugu_landing",
    "_render_ajalugu_result",
    "_render_ajalugu_unresolved",
    "_render_burden_disambiguation",
    "_render_burden_landing",
    "_render_burden_result",
    "_render_burden_unresolved",
    "_render_court_practice_disambiguation",
    "_render_court_practice_landing",
    "_render_court_practice_result",
    "_render_court_practice_unresolved",
    "_render_disambiguation",
    "_render_draft_backed_result",
    "_render_eu_disambiguation",
    "_render_eu_transposition_result",
    "_render_eu_unresolved",
    "_render_padevused_disambiguation",
    "_render_padevused_landing",
    "_render_padevused_result",
    "_render_padevused_unresolved",
    "_render_sanctions_disambiguation",
    "_render_sanctions_landing",
    "_render_sanctions_result",
    "_render_sanctions_unresolved",
    "_render_similarity_disambiguation",
    "_render_similarity_landing",
    "_render_similarity_result",
    "_render_unresolved",
    "_resolve_refs",
    "_resolved_key",
    "_resolved_label",
    "_resolved_type_label",
    "_result_actions",
    "_riigikohtu_section",
    "_risk_and_recommendation",
    "_sanction_act_cell",
    "_sanction_default_cell",
    "_sanction_enforcement_cell",
    "_sanction_penalty_cell",
    "_sanction_penalty_phrase",
    "_sanction_provision_cell",
    "_sanction_results_block",
    "_sanction_summary_line",
    "_sanction_type_cell",
    "_sanctions_actions",
    "_sanctions_evidence_block",
    "_sanctions_link",
    "_sanctions_scope_block",
    "_scope_form",
    "_select_dispatchable",
    "_seotud_eelnoud_section",
    "_similarity_actions",
    "_similarity_evidence_block",
    "_similarity_link",
    "_similarity_reason_badges",
    "_similarity_results_block",
    "_similarity_row_link",
    "_split_link_query",
    "_sr",
    "_status_action_cell",
    "_status_badge_cell",
    "_step_label",
    "_sub_section",
    "_temporal_scope_select",
    "_try_parse_uuid",
    "_type_label",
    "_type_localname",
    "_workflow_card",
    "_workflow_link",
    "ajalugu_page",
    "analyysikeskus_page",
    "el_ulevott_page",
    "halduskoormus_page",
    "kohtupraktika_page",
    "moju_poliitikamottest_analyze",
    "moju_poliitikamottest_extract",
    "moju_poliitikamottest_page",
    "normi_mojuahel_page",
    "padevused_page",
    "sanktsioonid_page",
    "sarnasus_page",
    "register_analyysikeskus_routes",
]


def register_analyysikeskus_routes(rt) -> None:  # type: ignore[no-untyped-def]
    """Register Analüüsikeskus routes on the FastHTML route decorator *rt*.

    Mirrors the original monolith\'s registration order so the route table is
    byte-for-byte identical (pinned by
    ``tests/test_analyysikeskus_route_parity.py``). Auth is enforced by the
    global ``auth_before`` middleware — none of these paths are in
    ``SKIP_PATHS``.
    """
    rt("/analyysikeskus", methods=["GET"])(analyysikeskus_page)
    rt("/analyysikeskus/normi-mojuahel", methods=["GET"])(normi_mojuahel_page)
    rt("/analyysikeskus/el-ulevott", methods=["GET"])(el_ulevott_page)
    rt("/analyysikeskus/sanktsioonid", methods=["GET"])(sanktsioonid_page)
    rt("/analyysikeskus/kohtupraktika", methods=["GET"])(kohtupraktika_page)
    rt("/analyysikeskus/halduskoormus", methods=["GET"])(halduskoormus_page)
    rt("/analyysikeskus/padevused", methods=["GET"])(padevused_page)
    rt("/analyysikeskus/ajalugu", methods=["GET"])(ajalugu_page)
    rt("/analyysikeskus/sarnasus", methods=["GET"])(sarnasus_page)
    # #814 Phase 2b — policy-intent → impact flow (three-step HTMX).
    rt("/analyysikeskus/moju-poliitikamottest", methods=["GET"])(moju_poliitikamottest_page)
    rt("/analyysikeskus/moju-poliitikamottest/extract", methods=["POST"])(
        moju_poliitikamottest_extract
    )
    rt("/analyysikeskus/moju-poliitikamottest/analyze", methods=["POST"])(
        moju_poliitikamottest_analyze
    )
